name = "CPlusCraft"
author = "Gaspard Wierzbinski"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7247d06fb9cc8fe7948c24b38e11ddac99be18c9b990e2ae80a9231a567ef2d4"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.4"]
